import React, { useEffect, useMemo, useRef, useState } from 'react';

const TOKEN_KEY='nova_token_v3';
const THEME_KEY='nova_theme_v3';
const api=async(path,opts={})=>{
  const token=localStorage.getItem(TOKEN_KEY); const headers={...(opts.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(opts.headers||{})};
  if(token) headers.Authorization=`Bearer ${token}`;
  const r=await fetch(path,{...opts,headers}); let data={}; try{data=await r.json()}catch{}
  if(!r.ok) throw new Error(data.error||`Request failed (${r.status})`); return data;
};

function App(){
  const [user,setUser]=useState(null); const [boot,setBoot]=useState(true); const [theme,setTheme]=useState(localStorage.getItem(THEME_KEY)||'dark');
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem(THEME_KEY,theme)},[theme]);
  useEffect(()=>{(async()=>{const t=localStorage.getItem(TOKEN_KEY);if(t){try{const d=await api('/api/auth/me');setUser(d.user)}catch{localStorage.removeItem(TOKEN_KEY)}}setBoot(false)})()},[]);
  const logout=()=>{localStorage.removeItem(TOKEN_KEY);setUser(null)};
  if(boot) return <div className="splash"><div className="logoMark">✦</div><b>NOVA AI</b><span>Loading...</span></div>;
  if(!user) return <Auth onLogin={setUser} theme={theme} setTheme={setTheme}/>;
  if(user.role==='admin') return <Admin user={user} logout={logout} theme={theme} setTheme={setTheme}/>;
  return <Workspace user={user} logout={logout} theme={theme} setTheme={setTheme}/>;
}

function Auth({onLogin,theme,setTheme}){
 const [mode,setMode]=useState('login'); const [type,setType]=useState('student'); const [form,setForm]=useState({name:'',email:'',password:'',studentId:''}); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 const submit=async e=>{e.preventDefault();setError('');setBusy(true);try{const path=mode==='login'?'/api/auth/login':'/api/auth/register';const body=mode==='login'?{email:form.email,password:form.password}:{...form,accountType:type};const d=await api(path,{method:'POST',body:JSON.stringify(body)});localStorage.setItem(TOKEN_KEY,d.token);onLogin(d.user)}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <div className="authPage"><div className="authBrand"><div className="logoMark">✦</div><h1>NOVA AI</h1><p>Your intelligent AI workspace for study, coding, research and everyday questions.</p><div className="featureRow"><span>AI Chat</span><span>Library</span><span>History</span></div></div><div className="authCard"><div className="tabs"><button className={mode==='login'?'active':''} onClick={()=>{setMode('login');setError('')}}>Login</button><button className={mode==='register'?'active':''} onClick={()=>{setMode('register');setError('')}}>Register</button></div><h2>{mode==='login'?'Welcome back':'Create your account'}</h2><p className="muted">{mode==='login'?'Sign in to continue to NOVA AI.':'Register for your NOVA AI workspace.'}</p><form onSubmit={submit}>
 {mode==='register'&&<input placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/>}
 {mode==='register'&&<div className="typeSwitch"><button type="button" className={type==='student'?'selected':''} onClick={()=>setType('student')}>Student</button><button type="button" className={type==='public'?'selected':''} onClick={()=>setType('public')}>Public</button></div>}
 {mode==='register'&&type==='student'&&<input placeholder="Student ID" value={form.studentId} onChange={e=>setForm({...form,studentId:e.target.value})} required/>}
 <input type="email" placeholder="Email address" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/>
 {error&&<div className="error">{error}</div>}<button className="primary wide" disabled={busy}>{busy?'Please wait...':mode==='login'?'Login':'Create account'}</button></form><button className="themeMini" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'☀ Light mode':'◐ Dark mode'}</button></div></div>
}

function Workspace({user,logout,theme,setTheme}){
 const [page,setPage]=useState('home'); const [chats,setChats]=useState([]); const [active,setActive]=useState(null); const [messages,setMessages]=useState([]); const [input,setInput]=useState(''); const [busy,setBusy]=useState(false); const [library,setLibrary]=useState([]); const [selectedFile,setSelectedFile]=useState(null); const [notice,setNotice]=useState(''); const bottom=useRef(null); const fileRef=useRef(null);
 const loadChats=async()=>{try{const d=await api('/api/chats');setChats(d.chats);if(d.chats.length&&!active)selectChat(d.chats[0].id)}catch(e){setNotice(e.message)}};
 const loadLibrary=async()=>{try{const d=await api('/api/library');setLibrary(d.files)}catch(e){setNotice(e.message)}};
 useEffect(()=>{loadChats();loadLibrary()},[]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth'})},[messages,busy]);
 const selectChat=async id=>{setActive(id);setPage('home');try{const d=await api(`/api/chats/${id}/messages`);setMessages(d.messages)}catch(e){setNotice(e.message)}};
 const newChat=async()=>{try{const d=await api('/api/chats',{method:'POST',body:JSON.stringify({title:'New Chat'})});setChats(x=>[d.chat,...x]);setActive(d.chat.id);setMessages([]);setPage('home')}catch(e){setNotice(e.message)}};
 const send=async()=>{if(!input.trim()||busy)return;const text=input.trim();setInput('');setBusy(true);setNotice('');const optimistic={id:`temp-${Date.now()}`,role:'user',content:text,createdAt:new Date().toISOString()};setMessages(m=>[...m,optimistic]);try{const d=await api('/api/chat',{method:'POST',body:JSON.stringify({chatId:active,message:text,fileId:selectedFile?.id})});setActive(d.chat.id);setMessages(m=>[...m.filter(x=>x.id!==optimistic.id),optimistic,d.message]);setChats(prev=>{const without=prev.filter(c=>c.id!==d.chat.id);return [d.chat,...without]});setSelectedFile(null)}catch(e){setMessages(m=>m.filter(x=>x.id!==optimistic.id));setNotice(e.message)}finally{setBusy(false)}};
 const onKey=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};
 const upload=async e=>{const file=e.target.files?.[0];if(!file)return;setNotice('Uploading...');const fd=new FormData();fd.append('file',file);try{const d=await api('/api/upload',{method:'POST',body:fd});setLibrary(x=>[d.file,...x]);setSelectedFile(d.file);setNotice(`${d.file.name} attached.`)}catch(err){setNotice(err.message)}e.target.value=''};
 const removeFile=async id=>{try{await api(`/api/library/${id}`,{method:'DELETE'});setLibrary(x=>x.filter(f=>f.id!==id));if(selectedFile?.id===id)setSelectedFile(null)}catch(e){setNotice(e.message)}};
 const deleteChat=async id=>{try{await api(`/api/chats/${id}`,{method:'DELETE'});const left=chats.filter(c=>c.id!==id);setChats(left);if(active===id){setActive(left[0]?.id||null);setMessages(left[0]?((await api(`/api/chats/${left[0].id}/messages`)).messages):[])} }catch(e){setNotice(e.message)}};
 const greeting=useMemo(()=>`Welcome to NOVA AI, ${user.name.split(' ')[0]} 👋`,[user.name]);
 return <div className="appShell"><aside className="sidebar"><div className="brand"><span className="logoMark small">✦</span><b>NOVA AI</b></div><button className="newChat" onClick={newChat}>＋ New Chat</button><div className="sideLabel">RECENT CHATS</div><div className="chatList">{chats.length?chats.map(c=><div key={c.id} className={`chatItem ${active===c.id?'active':''}`}><button onClick={()=>selectChat(c.id)}>{c.title}</button><button className="trash" onClick={()=>deleteChat(c.id)} title="Delete chat">×</button></div>):<div className="emptySide">No chats yet</div>}</div><div className="sidebarBottom"><button onClick={()=>setPage('library')} className={page==='library'?'navActive':''}>▣ Library</button><button onClick={()=>setPage('settings')} className={page==='settings'?'navActive':''}>⚙ Settings</button><button onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'☀ Light theme':'◐ Dark theme'}</button><button onClick={logout}>↪ Logout</button></div></aside><main className="main"><header className="topbar"><div><b>{page==='home'?'NOVA AI':page==='library'?'Library':'Settings'}</b></div><div className="profile">{user.name} <span className="avatar">{user.name[0]}</span></div></header>{notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
 {page==='library'?<Library files={library} removeFile={removeFile}/>:page==='settings'?<Settings user={user} theme={theme} setTheme={setTheme} logout={logout}/>:<>
 <section className={`chatArea ${messages.length?'hasMessages':''}`}>{!messages.length?<div className="welcome"><div className="welcomeLogo">✦</div><h1>{greeting}</h1><p>Your intelligent AI assistant for learning, coding, research and everyday questions.</p><h3>What can I help you with?</h3><div className="quickGrid"><Quick icon="📚" title="Study Help" text="Explain a topic or prepare for exams" onClick={()=>setInput('Help me understand this topic: ')}/><Quick icon="💻" title="Coding" text="Debug, explain or build code" onClick={()=>setInput('Help me with this coding problem: ')}/><Quick icon="📄" title="Upload File" text="Ask questions about a document" onClick={()=>fileRef.current?.click()}/><Quick icon="🔎" title="Research" text="Explore a topic clearly" onClick={()=>setInput('Help me research this topic: ')}/></div></div>:<div className="messages">{messages.map(m=><Message key={m.id} m={m}/>) }{busy&&<div className="message assistant"><div className="msgAvatar">✦</div><div className="bubble typing">NOVA AI is thinking<span>•••</span></div></div>}<div ref={bottom}/></div>}</section>
 <div className="composerWrap"><div className="composer">{selectedFile&&<div className="attachment"><span>📎 {selectedFile.name}</span><button onClick={()=>setSelectedFile(null)}>×</button></div>}<div className="inputRow"><button className="attach" onClick={()=>fileRef.current?.click()} title="Upload file">＋</button><input ref={undefined} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={onKey} placeholder="Ask NOVA AI anything..."/><button className="send" onClick={send} disabled={busy||!input.trim()}>➤</button></div><input ref={fileRef} type="file" hidden onChange={upload}/></div><small>NOVA AI can make mistakes. Verify important information.</small></div></>}</main></div>
}

function Quick({icon,title,text,onClick}){return <button className="quick" onClick={onClick}><span>{icon}</span><div><b>{title}</b><small>{text}</small></div></button>}
function Message({m}){return <div className={`message ${m.role}`}>{m.role==='assistant'&&<div className="msgAvatar">✦</div>}<div className="bubble">{m.content.split(/```/).map((part,i)=>i%2?<pre key={i}><code>{part.replace(/^\w+\n/,'')}</code></pre>:<span key={i}>{part.split('\n').map((x,j)=><React.Fragment key={j}>{x}{j<m.content.split('\n').length-1&&<br/>}</React.Fragment>)}</span>)}</div></div>}
function Library({files,removeFile}){return <div className="pageContent"><div className="pageHead"><div><h1>Library</h1><p>Your uploaded files are stored here and can be used as context in chats.</p></div></div>{!files.length?<div className="emptyCard"><div className="bigIcon">▣</div><h2>Your library is empty</h2><p>Upload a document from the chat composer to see it here.</p></div>:<div className="fileGrid">{files.map(f=><div className="fileCard" key={f.id}><div className="fileIcon">{f.name.match(/\.(jpg|jpeg|png|webp)$/i)?'🖼':'📄'}</div><div className="fileInfo"><b>{f.name}</b><small>{formatBytes(f.size)} · {new Date(f.createdAt).toLocaleDateString()}</small>{f.hasText&&<small className="green">Text available to AI</small>}</div><button onClick={()=>removeFile(f.id)}>Delete</button></div>)}</div>}</div>}
function Settings({user,theme,setTheme,logout}){return <div className="pageContent"><h1>Settings</h1><p className="muted">Manage your NOVA AI preferences and account.</p><div className="settingsGrid"><div className="settingCard"><h3>Appearance</h3><p>Choose how NOVA AI looks.</p><div className="themeOptions"><button className={theme==='dark'?'selected':''} onClick={()=>setTheme('dark')}>◐ Dark</button><button className={theme==='light'?'selected':''} onClick={()=>setTheme('light')}>☀ Light</button></div></div><div className="settingCard"><h3>Account</h3><p><b>{user.name}</b><br/>{user.email}<br/>{user.accountType==='student'?`Student ID: ${user.studentId}`:'Public account'}</p></div><div className="settingCard"><h3>AI Model</h3><p>Provider: Ollama<br/>Model: llama3.2<br/>Language: English by default</p></div><div className="settingCard"><h3>Session</h3><p>Your account is securely authenticated with a session token.</p><button className="danger" onClick={logout}>Log out</button></div></div></div>}
function Admin({user,logout,theme,setTheme}){const [stats,setStats]=useState(null);const [users,setUsers]=useState([]);const [error,setError]=useState('');const load=async()=>{try{const [s,u]=await Promise.all([api('/api/admin/stats'),api('/api/admin/users')]);setStats(s);setUsers(u.users)}catch(e){setError(e.message)}};useEffect(()=>{load()},[]);const remove=async id=>{if(!confirm('Delete this user?'))return;try{await api(`/api/admin/users/${id}`,{method:'DELETE'});load()}catch(e){setError(e.message)}};return <div className="adminShell"><header className="adminTop"><div className="brand"><span className="logoMark small">✦</span><b>NOVA AI</b><span className="adminBadge">ADMIN</span></div><div className="adminActions"><button onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'☀':'◐'}</button><span>{user.name}</span><button onClick={logout}>Logout</button></div></header><main className="adminMain"><div className="adminWelcome"><div><p className="eyebrow">ADMIN CONSOLE</p><h1>Welcome, {user.name.split(' ')[0]} 👋</h1><p>Manage NOVA AI users and monitor system status.</p></div><button className="refresh" onClick={load}>↻ Refresh</button></div>{error&&<div className="error">{error}</div>}<div className="stats">{[['Total Users',stats?.stats.users??'—','◉'],['Students',stats?.stats.students??'—','🎓'],['Public',stats?.stats.publicUsers??'—','◎'],['Chats',stats?.stats.chats??'—','💬']].map(x=><div className="stat" key={x[0]}><span>{x[2]}</span><small>{x[0]}</small><strong>{x[1]}</strong></div>)}</div><div className="system"><div><b>System Status</b><span className="statusDot">● Online</span></div><div className="statusItems"><span>Server <b>Online</b></span><span>Database <b>Online</b></span><span>Ollama <b className={stats?.ollama?.connected?'ok':'bad'}>{stats?.ollama?.connected?'Connected':'Offline'}</b></span><span>Model <b>{stats?.ollama?.model||'llama3.2'}</b></span></div></div><section className="usersPanel"><div className="panelHead"><div><h2>Registered Users</h2><p>Accounts currently registered in NOVA AI.</p></div></div><div className="tableWrap"><table><thead><tr><th>Name</th><th>Email</th><th>Type</th><th>Student ID</th><th>Created</th><th>Action</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.name}</b>{u.role==='admin'&&<span className="adminTag">Admin</span>}</td><td>{u.email}</td><td>{u.accountType}</td><td>{u.studentId||'—'}</td><td>{new Date(u.createdAt).toLocaleDateString()}</td><td>{u.role==='admin'?<span className="protected">Protected</span>:<button className="deleteBtn" onClick={()=>remove(u.id)}>Delete</button>}</td></tr>)}</tbody></table></div></section></main></div>}
function formatBytes(n){if(!n)return'0 B';const u=['B','KB','MB','GB'];const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),3);return`${(n/1024**i).toFixed(i?1:0)} ${u[i]}`}
export default App;
